### ISSUE TITLE
Doesn't work with Typescript 2.6.2 or higher / Angular Package Format

### ISSUE THREAD

**Issue by mwawrusch** [SamirHodzic/ngx-embed-video#7]
I'll get this
```
ERROR in ./node_modules/ngx-embed-video/index.ts
Module build failed: Error: ..../node_modules/ngx-embed-video/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/...../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:677:23)
    at plugin.done.then (...../node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/ngx-embed-video/src/embed-video.service.ts
Module build failed: Error:..../node_modules/ngx-embed-video/src/embed-video.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
**The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).**
    at AngularCompilerPlugin.getCompiledFile (/...../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:677:23)
    at plugin.done.then (....../node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by mwawrusch** [comment]
Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv)

**Comment by sixtoad** [comment]
#11

**Comment by bostondevin** [comment]
+1

**Comment by rktvsiim** [comment]
Same problem. Angular 5.2.4 and TypeScript 2.6.2

**Comment by kunal105** [comment]
Same error in angular 6 while doing a production build. Works on dev. Please help

**Comment by Moppet12** [comment]
I just updated to 1.0 but still facing this issue on ng build, my angular version is 5, any clue @SamirHodzic ?

**Comment by SamirHodzic** [comment]
@Moppet12 should work with Angular6+.
